global using Core.Entites;
global using System.Collections.Generic;
global using System.Threading.Tasks;
global using System.Linq.Expressions;
global using Core.Specifications;
global using Microsoft.AspNetCore.Identity;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Core.Entites.OrderAggregate;
